spring:
  docker:
    compose:
      enabled: true
      file: ./compose.yaml

# --- LOCAL DEVELOPMENT OVERRIDES ---
jwt:
  secret: "TXlTdXBlclNlY3JldEtleVRoYXRJc0F0TGVhc3QzMkJ5dGVzTG9uZw==" # Hardcoded 32-byte Base64 key
  cookie:
    secure: false    # Allow cookies over HTTP for local testing
    same-site: "Lax" # Allow React on port 5173 to talk to Spring on 8080