spring:
  docker:
    compose:
      enabled: true
      file: ./compose.yaml

# --- LOCAL DEVELOPMENT OVERRIDES ---
app:
  seed:
    enabled: true
  redis:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  cookie:
    secure: false    # Allow cookies over HTTP for local testing
    same-site: "Lax" # Allow React on port 5173 to talk to Spring on 8080
